//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p_0_Restaurant_Reviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string cusername { get; set; }
        public string cpassword { get; set; }
        public string ausername { get; set; }
        public string apassword { get; set; }
        public System.DateTime AccountCreated { get; set; }
    }
}
